### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] set up HTML skeleton
- [x] set up style.css and link it
- [x] set up main.js and link it
- [x] add `<img>` of a car to `<body>`
- [x] (style.css) set `<img>` position: absolute
- [x] ensure that car is in the L-hand corner of screen
- [x] set background color
- [x] get rid of extra styling that doesn't do anything
