### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.
Use the style property of element objects to change your car's top and left box offset styles.
Move your car every 16 milliseconds for a smooth movement.

## ✅ Task List

- [x] put `eventListener` on `document` obj and listen for a 'keydown' event on spacebar
- [x] in `eventListener` function, start interval (`setinterval`) 
- [ ] in `setInterval` function: change the `top` and `left` `box offset` values and increment the `x` and `y` variables
- [ ] set interval to "16"
