### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [ ] define function named `multiDirection`
- [x] define function that sets an interval where carro.x is incrimented by 10px and assign interval to the variable `int`
- [x] define function that sets an interval where carro.x is incrimented by -10px and assign interval to the variable `int`
- [x] define function that sets an interval where carro.y is incrimented by 10px and assign interval to the variable `int`
- [x] define function that sets an interval where carro.y is incrimented by -10px and assign interval to the variable `int`
- [x] define a function that clears intervals using `clearInterval(int)`
- [x] in function code block add the following if...else statements and responses:
- [ ] if `(rotation === 0)` --> `clearInterval(int)` ;carro.x gets incrimented by 10px; `setInterval`
- [ ] if `(rotation === 90)` --> carro.y gets incrimented by 10px
- [ ] if `(rotation === 180)` --> carro.x gets incrimented by -10px
- [ ] if `(rotation === 270)` --> carro.y gets incrimented by -10px
